//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHSPatServ
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUMBEROFPATIENT
    {
        public int ID { get; set; }
        public string Organisation_Name { get; set; }
        public string OrganisationCode { get; set; }
        public string Parent_Name { get; set; }
        public Nullable<int> Ref_Parent_ID { get; set; }
        public Nullable<int> Total_Patients { get; set; }
    }
}
